accounts/urls.py
from django.urls import path
from accounts.views import (
    LoginView,
    SignUpView,
    LogoutView,
    RecoveryPasswordView,
    SetPasswordView,
)


app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "recovery-password/", RecoveryPasswordView.as_view(), name="recovery_password"
    ),
    path(
        "set-password/<uidb64>/<token>/", SetPasswordView.as_view(), name="set_password"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("video_summary.urls", namespace="video_summary")),
]

video_summary/urls.py
from django.urls import path
from video_summary.views import MainView, VideoSummaryView, PostListView


app_name = "video_summary"
urlpatterns = [
    path("", MainView.as_view(), name="main"),
    path("video-summary/", VideoSummaryView.as_view(), name="video_summary"),
    path("posts/", PostListView.as_view(), name="post_list"),
]

templates/partials/footer.html
<!-- Footer -->
<footer>
    <p class="mt-10 bg-sky-600 p-2 text-center text-sm text-white">
        Powerd by <a href="https://www.linkedin.com/in/ijavadddd/" class="text-blue-200 hover:underline">@ijavadddd</a>
    </p>
</footer>

templates/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://kit.fontawesome.com/b50b841b1e.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@tailwindcss/browser@4"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/partials/messages.html
{% for message in messages %}
    {% if message %}
        <p class="{{ message.tags }} py-2 px-3 mb-2 text-center rounded-b-lg border-t-5">{{ message }}</p>
    {% endif %}
{% endfor %}

templates/partials/navbar.html
<!-- Navbar -->
<nav class="bg-sky-600 p-4 text-white">
    <div class="container mx-auto flex items-center justify-between max-w-3xl">
        <h1 class="text-3xl font-bold">استخراج متن از یوتیوب</h1>
        <div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'video_summary:post_list' %}" class="rounded-lg bg-teal-600 px-4 py-2 shadow-md hover:bg-teal-700 inline-block m-2">پنل کاربری</a>
            <a href="{% url 'accounts:logout' %}" class="rounded-lg bg-teal-600 px-4 py-2 shadow-md hover:bg-teal-700 inline-block m-2">خروج</a>
            {% else %}
            <a href="{% url 'accounts:login' %}" class="rounded-lg bg-teal-600 px-4 py-2 shadow-md hover:bg-teal-700 inline-block m-2">ورود</a>
            {% endif %}
        </div>
    </div>
</nav>
{% include 'partials/messages.html' %}

templates/partials/script.html
{% load static %}
<script src="{% static 'js/index.js' %}"></script>